-- Setup
CREATE WAREHOUSE COMPUTE_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE ECOMMERCE_DB;

CREATE SCHEMA RAW_SCHEMA;
CREATE SCHEMA CLEAN_SCHEMA;
CREATE SCHEMA ANALYTICS_SCHEMA;

-- Raw Table
CREATE OR REPLACE TABLE RAW_SCHEMA.ORDERS_RAW (
    ORDER_ID STRING,
    CUSTOMERNAME STRING,
    STATE STRING,
    CITY STRING,
    AMOUNT FLOAT,
    CATEGORY STRING,
    SUB_CATEGORY STRING,
    EVENT_ID STRING,
    INGESTION_TIME TIMESTAMP
);

-- File Format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

-- Storage Integration
CREATE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = ('s3://project-ecommerce-pipeline/raw/orders/');

-- Stage
CREATE OR REPLACE STAGE S3_STAGE
URL = 's3://project-ecommerce-pipeline/raw/orders/'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = CSV_FORMAT;

-- Snowpipe
CREATE OR REPLACE PIPE ORDERS_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RAW_SCHEMA.ORDERS_RAW
FROM (
    SELECT
        $1,
        $3,
        $4,
        $5,
        $6,
        $9,
        $10,
        UUID_STRING(),
        CURRENT_TIMESTAMP()
    FROM @S3_STAGE
)
FILE_FORMAT = CSV_FORMAT;

-- Stream
CREATE OR REPLACE STREAM ORDERS_STREAM
ON TABLE RAW_SCHEMA.ORDERS_RAW;

-- Clean Table(Target Table)
CREATE OR REPLACE TABLE CLEAN_SCHEMA.ORDERS_CLEAN
AS SELECT * FROM RAW_SCHEMA.ORDERS_RAW WHERE 1=0;

-- Task
CREATE OR REPLACE TASK ORDERS_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '5 MINUTE'
AS
INSERT INTO CLEAN_SCHEMA.ORDERS_CLEAN
SELECT *
FROM ORDERS_STREAM
WHERE METADATA$ACTION = 'INSERT';

ALTER TASK ORDERS_TASK RESUME;

-- Final Table
CREATE OR REPLACE TABLE CLEAN_SCHEMA.ORDERS_FINAL AS
SELECT *
FROM (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY ORDER_ID
               ORDER BY INGESTION_TIME DESC
           ) rn
    FROM CLEAN_SCHEMA.ORDERS_CLEAN
)
WHERE rn = 1;

-- KPI's
-- TOTAL_REVENUE
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.TOTAL_REVENUE AS
SELECT
    SUM(AMOUNT) AS TOTAL_REVENUE
FROM ANALYTICS_SCHEMA.ORDERS_FINAL;

-- REVENUE_BY_STATE
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.REVENUE_BY_STATE AS
SELECT
    STATE,
    SUM(AMOUNT) AS TOTAL_REVENUE
FROM CLEAN_SCHEMA.ORDERS_DEDUP
GROUP BY STATE;

-- TOP_CITIES
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.TOP_CITIES AS
SELECT
    CITY,
    SUM(AMOUNT) AS REVENUE
FROM ANALYTICS_SCHEMA.ORDERS_FINAL
GROUP BY CITY
ORDER BY REVENUE DESC;

-- CATEGORY_PERFORMANCE
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.CATEGORY_PERFORMANCE AS
SELECT
    CATEGORY,
    SUM(AMOUNT) AS TOTAL_SALES
FROM CLEAN_SCHEMA.ORDERS_DEDUP
GROUP BY CATEGORY;

-- SUBCATEGORY_PERFORMANCE
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.SUBCATEGORY_PERFORMANCE AS
SELECT
    CATEGORY,
    SUB_CATEGORY,
    SUM(AMOUNT) AS TOTAL_SALES
FROM ANALYTICS_SCHEMA.ORDERS_FINAL
GROUP BY CATEGORY, SUB_CATEGORY
ORDER BY TOTAL_SALES DESC;

-- DAILY_SALES
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.DAILY_SALES AS
SELECT
    DATE(INGESTION_TIME) AS ORDER_DATE,
    SUM(AMOUNT) AS DAILY_REVENUE
FROM ANALYTICS_SCHEMA.ORDERS_FINAL
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;

-- AVG_ORDER_VALUE
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.AVG_ORDER_VALUE AS
SELECT
    AVG(AMOUNT) AS AVG_ORDER_VALUE
FROM ANALYTICS_SCHEMA.ORDERS_FINAL;

-- TOTAL_ORDERS
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.TOTAL_ORDERS AS
SELECT
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM ANALYTICS_SCHEMA.ORDERS_FINAL;

-- TOP_PRODUCTS
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.TOP_PRODUCTS AS
SELECT
    SUB_CATEGORY,
    SUM(AMOUNT) AS REVENUE
FROM ANALYTICS_SCHEMA.ORDERS_FINAL
GROUP BY SUB_CATEGORY
ORDER BY REVENUE DESC;

-- CUSTOMER_COUNT
CREATE OR REPLACE VIEW ANALYTICS_SCHEMA.CUSTOMER_COUNT AS
SELECT
    COUNT(DISTINCT CUSTOMERNAME) AS TOTAL_CUSTOMERS
FROM ANALYTICS_SCHEMA.ORDERS_FINAL;

-- Stored Procedure
CREATE OR REPLACE PROCEDURE PROCESS_DATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
INSERT INTO ANALYTICS_SCHEMA.REVENUE_BY_STATE
SELECT STATE, SUM(AMOUNT)
FROM CLEAN_SCHEMA.ORDERS_DEDUP
GROUP BY STATE;
$$;

